apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccination-alert-ui
spec:
  selector:
    matchLabels:
      app: vaccination-alert-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: vaccination-alert-ui
        tier: vaccination-alert-ui
    spec:
     containers:
     - name: vaccination-alert-ui
       image: "shashimls276/vaccination-ui:16"
       ports:
       - containerPort: 8080        

---
apiVersion: v1
kind: Service
metadata:
  name: vaccination-alert-ui
  labels:
    app: vaccination-alert-ui
spec:
  selector:
    app: vaccination-alert-ui
  ports:
    - port: 80
      targetPort: 8082
  type: LoadBalancer